# Generated by Django 4.1.7 on 2023-04-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("PG", models.IntegerField()),
                ("PE", models.IntegerField()),
                ("PP", models.IntegerField()),
                ("GF", models.IntegerField()),
                ("GC", models.IntegerField()),
                ("DG", models.IntegerField()),
                ("puntos", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("contraseña", models.CharField(max_length=255)),
            ],
        ),
    ]
